name: qparking
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.8.0
  intl: ^0.19.0
  qr_flutter: ^4.1.0
  vibration: ^1.9.0
  font_awesome_flutter: 10.8.0
  local_auth: ^2.3.0
  google_maps_flutter: ^2.10.1
  geolocator: ^11.0.0

dependency_overrides:
  geolocator_android: 4.5.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/